# Uncomment the next line to define a global platform for your project
# platform :ios, '7.0'
platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'ByEnergyCharge' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ByEnergyCharge
inhibit_all_warnings!
pod 'JSONModel'
#pod 'MBProgressHUD'
pod 'MJRefresh'
pod 'Masonry'
pod 'ReactiveObjC', '~> 3.1.0'
pod 'MJExtension'
pod 'SDWebImage'
pod 'YYCache'
pod 'AFNetworking', '~> 3.2.1'
pod "ZBarSDK", :git => "https://github.com/phucdanghuu/ZBar.git", :commit => "b82be9cf11ec7045472e69b033461de438c1aa35"
pod 'SDCycleScrollView', '~> 1.71'
pod 'YYModel'
pod 'UMCAnalytics'
pod 'Bugly'
pod 'YPNavigationBarTransition'

  target 'ByEnergyChargeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ByEnergyChargeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# remove UIKit() rejected by AppStore
pre_install do |installer|
    puts 'pre_install begin....'
    dir_af = File.join(installer.sandbox.pod_dir('AFNetworking'), 'UIKit+AFNetworking')
    Dir.foreach(dir_af) {|x|
      real_path = File.join(dir_af, x)
      if (!File.directory?(real_path) && File.exists?(real_path))
        if((x.start_with?('UIWebView') || x == 'UIKit+AFNetworking.h'))
          File.delete(real_path)
          puts 'delete:'+ x
        end
      end
    }
    puts 'end pre_install.'
end

